# Render manifest: defines backend Docker web service and frontend static site
services:
  - type: web
    name: shorts-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    repo: https://github.com/<YOUR_ORG_OR_USER>/swift-shorts-downloader
    branch: blackboxai/fix-backend
    plan: free
    buildCommand: ""
    startCommand: ""

  - type: static
    name: shorts-frontend
    env: static
    repo: https://github.com/<YOUR_ORG_OR_USER>/swift-shorts-downloader
    branch: blackboxai/fix-backend
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      VITE_BACKEND_URL: https://avshortsdownloader.onrender.com
    plan: free
